apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rblo4egff-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/rblo4egff-java-quarkus-gitops